steps:
- name: node:18.13.0
  entrypoint: npm
  args: ["install"]
- name: node:18.13.0
  entrypoint: npm
  args: ["run", "create-env"]
  env:
  - 'NEXTAUTH_URL=${_NEXTAUTH_URL}'
  - 'NEXTAUTH_SECRET=fHSgo7+BXen9a6gnHrjfQDgscVkiu93gzJ8032au/bo=${_NEXTAUTH_SECRET=fHSgo7+BXen9a6gnHrjfQDgscVkiu93gzJ8032au/bo}'
  - 'NEXT_PUBLIC_LINKEDIN_CLIENT_ID=${_NEXT_PUBLIC_LINKEDIN_CLIENT_ID}'
  - 'LINKEDIN_CLIENT_SECRET=${_LINKEDIN_CLIENT_SECRET}'
  - 'NEXT_PUBLIC_LINKEDIN_REDIRECT_URI=${_NEXT_PUBLIC_LINKEDIN_REDIRECT_URI}'
  - 'NEXT_PUBLIC_LINKEDIN_STATE=${_NEXT_PUBLIC_LINKEDIN_STATE}'
  - 'GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID}'
  - 'GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET}'
  - 'GITHUB_CLIENT_ID=${_GITHUB_CLIENT_ID}'
  - 'GITHUB_CLIENT_SECRET=${_GITHUB_CLIENT_SECRET}'
  - 'BITBUCKET_CLIENT_ID=${_BITBUCKET_CLIENT_ID}'
  - 'BITBUCKET_CLIENT_SECRET=${_BITBUCKET_CLIENT_SECRET}'
  - 'BITBUCKET_OAUTH_CLIENT_ID=${_BITBUCKET_OAUTH_CLIENT_ID}'
  - 'PROJECT_ID=${_PROJECT_ID}'
  - 'PRIVATE_KEY_ID=${_PRIVATE_KEY_ID}'
  - 'PRIVATE_KEY=${_PRIVATE_KEY}'
  - 'CLIENT_EMAIL=${_CLIENT_EMAIL}'
  - 'CLIENT_ID=${_CLIENT_ID}'
  - 'AUTH_URI=${_AUTH_URI}'
  - 'TOKEN_URI=${_TOKEN_URI}'
  - 'AUTH_PROVIDER_X509_CERT_URL=${_AUTH_PROVIDER_X509_CERT_URL}'
  - 'CLIENT_X509_CERT_URL=${_CLIENT_X509_CERT_URL}'
  - 'PGSQL_USER=${_PGSQL_USER}'
  - 'PGSQL_PASSWORD=${_PGSQL_PASSWORD}'
  - 'PGSQL_HOST=${_PGSQL_HOST}'
  - 'PGSQL_PORT=${_PGSQL_PORT}'
  - 'PGSQL_DATABASE=${_PGSQL_DATABASE}'
  - 'DATABASE_URL=${_DATABASE_URL}'
  - 'NEXT_PUBLIC_RUDDERSTACK_CLIENT_WRITE_KEY=${_NEXT_PUBLIC_RUDDERSTACK_CLIENT_WRITE_KEY}'
  - 'NEXT_PUBLIC_RUDDERSTACK_CLIENT_DATAPLANE_URL=${_NEXT_PUBLIC_RUDDERSTACK_CLIENT_DATAPLANE_URL}'
  - 'RUDDERSTACK_SERVER_WRITE_KEY=${_RUDDERSTACK_SERVER_WRITE_KEY}'
  - 'RUDDERSTACK_SERVER_DATAPLANE_URL=${_RUDDERSTACK_SERVER_DATAPLANE_URL}'
  - 'GITLAB_CLIENT_ID=${_GITLAB_CLIENT_ID}'
  - 'GITLAB_CLIENT_SECRET=${_GITLAB_CLIENT_SECRET}'
  - 'CLARITY_ID=${_CLARITY_ID}'
- name: node:18.13.0
  entrypoint: npm
  args: ["run", "build"]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
timeout: '1600s'
